### ISSUE TITLE
Build PyTorch 1.12.0 or 1.13.0 on CC 3.0 GPU?

### ISSUE THREAD

**Issue by TechVillain** [dizcza/pytorch-sm30-docker#4] opened 2023-11-17 15:39 UTC
Is PyTorch 1.10.0 the highest version to be used with CUDA 10.2 on an Nvidia Compute Capability 3.0 GPU?

Or one can still build from source of PyTorch 1.12.0 or even 1.13.0 to be used on a CC 3.0 card?

Official PyTorch site seems to indicate, PyTorch can be built from source for sm_30 (CC 3.0) graphic cards until version 1.13.0. Version 2.0.0 drops support for sm_30 and CUDA 10.2 and below.

Is this right?

**Comment by dizcza** [comment] 2023-11-17 17:45
> Official PyTorch site seems to indicate, PyTorch can be built from source for sm_30 (CC 3.0) graphic cards until version 1.13.0. Version 2.0.0 drops support for sm_30 and CUDA 10.2 and below.

where is it stated?

I've tried compiling more recent pytorch versions and the issue happens with new operators in nccl that are not supported on sm_30 arch, and pytorch depends on them in newer versions.

I ain't saying that it's *impossible*. But rather improbable. Personally, I haven't seen any CUDA builds of pytorch with versions newer than in my dockerfile.

**Comment by dizcza** [comment] 2023-11-17 17:46
... I haven't seen any CUDA builds of pytorch with versions newer than in my dockerfile for sm_30

**Comment by TechVillain** [comment] 2023-11-18 01:17
In your dockerfile, you put version 1.10.2, which is the highest version of 1.10, in other words, you mean PyTorch>=1.11.0 will not work on sm_30 cards.

So, when you say you tried to compile more recent PyTorch, how did you fail? Did you fail to build a wheel file, or you successfully built a whl file but failed to pip install it? Which scenario?

I have a GTX 660m card of Kepler sm_30 in Windows 7 64 bit, so I tried to build a wheel of PyTorch 1.10.0 in Python 3.8 and CUDA 10.2 based on cuDNN 7.6.5, I succeeded, and the built torch is indeed using my GPU, everything is working.

However, when I use the same environment, tried to build PyTorch 1.12.0 and 1.13.0, I failed. There were nvcc errors occured in the compile process. I can't even get a whl file.

The sad thing is, when I visit the official PyTorch forum, there are quite a few people saying they successfully built a wheel for PyTorch 1.13.0 from their sm_30 machines, which hurt my feelings.

Did I do something wrong?

Could you share a bit about your compile process? Similiar to Mine?

**Comment by dizcza** [comment] 2023-11-18 07:27
> In your dockerfile, you put version 1.10.2, which is the highest version of 1.10, in other words, you mean PyTorch>=1.11.0 will not work on sm_30 cards.

~~Yes, that's what I meant.~~ Actually, no, I meant that PyTorch>=1.11.0 will not *get compiled* for sm_30 arch.

> However, when I use the same environment, tried to build PyTorch 1.12.0 and 1.13.0, I failed. There were nvcc errors occured in the compile process. I can't even get a whl file.

That's the same behavior I was getting. I didn't get a wheel. It failed somewhere in cuda files compilation while building pytorch sources.

> The sad thing is, when I visit the official PyTorch forum, there are quite a few people saying they successfully built a wheel for PyTorch 1.13.0 from their sm_30 machines, which hurt my feelings.

Why don't you kindly ask them to share a dockerfile or precise steps to reproduce?

**Comment by TechVillain** [comment] 2023-11-19 01:54
Please allow me several days to contact these forum influencers and wait for their response.

Once I have something, I will get back to you with one of the two results.

Result 1: I will share with you a 1.13.0 wheel compiled from sm_30 arch list, so you can test it out.

Result 2: Bad news! PyTorch>=1.11.0 can not be compiled from a CC 3.0 machine.

**Comment by TechVillain** [comment] 2023-11-19 02:30
A summary of what I have heard from the forum so far. 

1. Many people built their wheel not with docker, but with Anaconda environment + Visual Studio 2019 + cmd terminal, which has a higher chance of success.

2. Use this blog as a reference.

https://datagraphi.com/blog/post/2021/9/13/building-pytorch-from-source-on-windows-to-work-with-an-old-gpu

3. Try to use the lowest possible configuration, which is: Python 3.8 + CUDA 10.2 + cuDNN 7.6.5, will have better chance to succeed. Also, try to 'git checkout' 1.13.0 version, not 1.13.1 version, as small version may potentially get errors.

4. Before each compiling, always do this: uninstall and reinstall your Anaconda or Miniconda program, in order to have a fresh and unaffected 'base' environment. The 'base' env is actually affecting all your created envs, including your compiling env.

5. Someone mentioned, you can just download the official pre-made binaries, install on your sm_30 machine. Then you modify your own system, trick the wheel thinking your graphic card is sm_50 instead of 30, so the wheel will start to run without giving you the nonsense. I'm still waiting for some info on this. Have you tried this before?

6. If you are interested, you can also try this, the ultimate solution. 
First, find a sm_50 machine, or use a free cloud computer. 
Then set that machine exactly the same as your sm_30 machine, such as python, CUDA, cuDNN, and forced variables.
set TORCH_CUDA_ARCH_LIST=3.0
Finally, you go ahead build a 1.13.0 wheel on that 50 machine, copy that wheel back to your 30 machine, and enjoy!

Let me know if you succeed. I look forward to hearing some good news from you.

**Comment by dizcza** [comment] 2023-11-19 07:45
Sorry, I'm not interested in keeping this dockerfile with newer versions of Pytorch because I no longer use/have old GPU cards.

If you succeed in building the latest versions of Pytorch for sm_30, please share the bash script.

The blog you mentioned is (1) for Windows only and (2) does not provide a clean bash script that would do all steps without manually downloading something and extra steps.

Otherwise, I'll keep the old and working version of pytorch here.

**Comment by TechVillain** [comment] 2023-11-21 17:21
Previously, after you successfully built a wheel for PyTorch 1.10.2, and then install it to an environment, is your wheel working 100% of the time, or not?

When I tested my wheel of 1.10.0, quite often, CUDA stops running, and prompts an error.

> **OSError: [WinError 126] The specified module could not be found. Error loading "D:\AI\TEST-TORCH\lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies.**

Do you have any idea what causes this error?

**Comment by dizcza** [comment] 2023-11-21 17:37
> Previously, after you successfully built a wheel for PyTorch 1.10.2, and then install it to an environment, is your wheel working 100% of the time, or not?

It has been working well ever since, and I haven't had any issues with my dockerfile running on Ubuntu with a GPU 3.0 capability.

The issue you mentioned could be due to Windows intrinsics. Sorry, I have no idea what to do then. I always work on Unix systems and I cannot consult Windows guys when they face a problem. The fact that it fails "quite often" but not always makes it even more confusing - I have no clue why.

**Comment by TechVillain** [comment] 2023-11-24 07:04
You mentioned you have successfully built PyTorch 1.10 from source several times.

There is a fatal problem.

The official binary for PyTorch 1.10 is over 1 GB, with both PyTorch and a copy of CUDA 10.2 built into the wheel.

However, when you build from source, your 1.10 wheel is about 300 MB, only contains PyTorch, no CUDA copy.

It means, the wheel you built from source is NOT self-contained, but has to rely on the system CUDA to work. If the system changes, your environment is ruined.

I had this PyTorch 1.10 working in an env just fine. Then when I try to built 1.12 and 1.13, not only I failed, but also affected the settings of my system CUDA installation. Too bad. When I try to run the same 1.10 in the same env, it doesn't work anymore, because system CUDA is changed.

Have you experienced similiar conflicts between your PyTorch wheel and system CUDA?

Do you know how to build a PyTorch wheel with an isolated copy of CUDA inside, just like the official binary?

**Comment by dizcza** [comment] 2023-11-24 12:38
The CUDA version is fixed in the dockerfile and should not be changed. If you feel you can work out a newer version of CUDA or PyTorch, you're totally on your own, I cannot help.

> Have you experienced similiar conflicts between your PyTorch wheel and system CUDA?

No.

> Do you know how to build a PyTorch wheel with an isolated copy of CUDA inside, just like the official binary?

No.

**Closed as completed** 2023-11-27 08:58 UTC
